### PR TITLE
feat: redesign

### PR DESCRIPTION
**Pull request by fhennig**
preview here: https://github.com/stackabletech/documentation/pull/653

- colors updated
- fonts updated
- fonts are now pulled from fontsource instead of the deprecated typeface

### CODE REVIEW

**Comment by fhennig** [comment]
todo:
- ~~fix colors~~
- ~~replace roboto mono with noto mono (maybe, might look nicer in context, especially in flowing text)~~

**Comment by xeniape** [comment]
Just noting down something I noticed: In the website redesign when hovering over an item in the menu at the top, the dropdown menu seems to have a small shadow. I think it would be nice to have that as well in the docs for consistency.

image

**Comment by fhennig** [comment]
Thanks @xeniape , added it https://github.com/stackabletech/documentation-ui/pull/73/commits/45d3e639cbb5825af00d8439bcf749b1d4037a0b

**Review by xeniape — APPROVED** [review]
LGTM

**Comment by nightkr** [comment]
- Where'd darkmode go?
- Why is there so little contrast on the dropdowns? Off-white on white on white makes it hard to see where the click/hover zones are.
image

**Pull request merged**
