### PR TITLE
Add Secret operator to navbar

### PR DESCRIPTION
**Pull request by nightkr**

### CODE REVIEW

**Comment by nightkr** [comment]
Not sure that this is the right place for it to go, feels like we'd like to have some separation between product operators and "commons" operators.

**Review by sbernauer — APPROVED** [review]

**Comment by lfrancke** [comment]
I agree.....we might want some separation between products and things like opa & secret....
 but for now I think it's better to have it _somewhere_?

**Review by lfrancke — APPROVED** [review]

**Comment by nightkr** [comment]
Agreed.

**Pull request merged**
